language: java
before_install:
  - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install -y google-chrome-stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
