version: '3.3'

networks:
  www-external:
    internal: false
  www-internal:
    internal: true

services:
  liferay:
    image: liferay/commerce:1.1.4
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "8001:8000"
      - "8081:8080"
      - "11312:11311"
      - "12346:12345"
    environment:
      - CATALINA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"
    volumes:
      - "./configs/docker/files:/etc/liferay/mount/files"
      - "./bundles/deploy:/etc/liferay/mount/deploy"
      - "./bundles/osgi/modules:/opt/liferay/osgi/modules"
      - "./bundles/osgi/war:/opt/liferay/osgi/war"

volumes:
  liferay:
